server:
  servlet:
    context-path: /socket-transfer-server

spring:
  profiles:
    include: @profiles.active@

minio:
  endpoint: http://192.168.0.221:9000
  access-key: 0a75wAuJjOu4eDM2xw2p
  secret-key: s2ZvhoPCUnFLldFtRDTl9VRxv5TEzmoQc5dZYeUC
  bucket-name: 'mdsd-m350'