server:
  port: ${env.port.sts.api}
  tomcat:
    max-connections: 256
    connection-timeout: 20S
    accept-count: 56
    threads:
      max: 200
      min-spare: 10

spring:
  application:
    name: STS_LINUX
  boot:
    admin:
      client:
        url: http://127.0.0.1:20249
management:
  endpoints:
    web:
      exposure:
        include: '*'

# IP and port configuration
env:
  ip:
    sts: 192.168.0.221
    tyjw: 192.168.0.222
    jikupi: 192.168.14.120
  port:
    sts:
      api: 10240
      web_socket_server: 10241
      udp: 10242
      mqtt: 1883
    tyjw:
      api: 12000
      tcp: 13002
    jikupi:
      api: 8000
