knife4j:
  production: false
  enable: true
  basic:
    enable: false
    username: renren
    password: 2ZABCDEUgF
  setting:
    enableFooter: false
spring:
  application:
    name: mdtg-esp32-api
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mdsdcxyw3.mysql.rds.aliyuncs.com:3306/mdtg_esp32_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: robot_admin
      password: Medical@qwe123
      keep-alive: true
      keep-alive-between-time-millis: 120000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 6000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-return: false
      stat-view-servlet:
        enabled: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  data:
    redis:
      host: ${service-address.redis.ip}
      port: ${service-address.redis.port}
      password: ${service-address.redis.password}
      database: ${service-address.redis.database}
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms

service-address:
  mdtg:
    ip: 127.0.0.1
    port: 8001
  customer:
    ip: 127.0.0.1
    port: 8002
  mqtt:
    ip: 127.0.0.1
    port: 1883
    username: mdtg
    password: mdtg@123
  redis:
    ip: 192.168.0.12
    port: 6379
    password: Mdsd@2026
    database: 0
  minio:
    endpoint: http://192.168.0.12:9000
    access-key: Medical@Robot
    secret-key: Medical@Robot
    bucket-name: mdtg-esp32-api